exp_exec_prefix = /usr
exp_bindir = /usr/bin
exp_sbindir = /usr/sbin
exp_libdir = /usr/lib
exp_libexecdir = /usr/lib/apache2/modules
exp_mandir = /usr/share/man
exp_sysconfdir = /etc/apache2
exp_datadir = /usr/share/apache2
exp_installbuilddir = /usr/share/apache2/build
exp_errordir = /usr/share/apache2/error
exp_iconsdir = /usr/share/apache2/icons
exp_htdocsdir = /usr/share/apache2/default-site/htdocs
exp_manualdir = /usr/share/apache2/default-site/htdocs/manual
exp_cgidir = /usr/lib/cgi-bin
exp_includedir = /usr/include/apache2
exp_localstatedir = /var/lock/apache2
exp_runtimedir = /var/run/apache2
exp_logfiledir = /var/log/apache2
exp_proxycachedir = /var/cache/apache2/proxy
SHLTCFLAGS = -prefer-pic
LTCFLAGS = -prefer-non-pic -static
MKINSTALLDIRS = /usr/share/apache2/build/mkdir.sh
INSTALL = $(LIBTOOL) --mode=install /usr/share/apache2/build/install.sh -c
SSL_LIBS = -lssl -lcrypto
MPM_NAME = prefork
INSTALL_DSO = yes
progname = apache2
OS = unix
SHLIBPATH_VAR = LD_LIBRARY_PATH
AP_BUILD_SRCLIB_DIRS =
AP_CLEAN_SRCLIB_DIRS =
bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
cgidir = ${prefix}/usr/lib/cgi-bin
logfiledir = ${prefix}/var/log/apache2
exec_prefix = ${prefix}/usr
datadir = ${exec_prefix}/share/apache2
localstatedir = ${prefix}/var/lock/apache2
mandir = ${exec_prefix}/share/man
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/lib/apache2/modules
htdocsdir = ${prefix}/usr/share/apache2/default-site/htdocs
manualdir = ${htdocsdir}/manual
includedir = ${exec_prefix}/include/apache2
errordir = ${datadir}/error
iconsdir = ${datadir}/icons
sysconfdir = ${prefix}/etc/apache2
installbuilddir = ${prefix}/usr/share/apache2/build
runtimedir = ${prefix}/var/run/apache2
proxycachedir = ${prefix}/var/cache/apache2/proxy
other_targets = suexec
progname = apache2
prefix =
AWK = mawk
CC = sparc-linux-gnu-gcc
CPP = sparc-linux-gnu-gcc -E
CXX =
CXXFLAGS = -g -O2
LTFLAGS = --silent
LDFLAGS =
LT_LDFLAGS =
SH_LDFLAGS =
LIBS =
DEFS =
INCLUDES =
NOTEST_CXXFLAGS =
NOTEST_LDFLAGS =
NOTEST_LIBS =
EXTRA_CXXFLAGS =
EXTRA_LDFLAGS =
EXTRA_LIBS = -lm -L/usr/lib -lpcre
EXTRA_INCLUDES = -I$(includedir) -I. -I/usr/include/apr-1.0 -I/usr/include/postgresql
LIBTOOL = /usr/share/apr-1.0/build/libtool --silent
SHELL = /bin/sh
RSYNC = /usr/bin/rsync
SH_LIBS =
SH_LIBTOOL = $(LIBTOOL)
MK_IMPLIB =
MKDEP = $(CC) -MM
INSTALL_PROG_FLAGS =
APR_BINDIR = /usr/bin
APR_INCLUDEDIR = /usr/include/apr-1.0
APR_VERSION = 1.2.11
APR_CONFIG = /usr/bin/apr-1-config
APU_BINDIR = /usr/bin
APU_INCLUDEDIR = /usr/include/apr-1.0
APU_VERSION = 1.2.7
APU_CONFIG = /usr/bin/apu-1-config
CPPFLAGS = -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -DLINUX=2 -D_REENTRANT -I. -I$(includedir) -I/usr/include/apr-1.0 -I/usr/include/postgresql 
CFLAGS = -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -DLINUX=2 -D_REENTRANT -I/usr/include/apr-1.0 -I/usr/include/openssl -I/usr/include/postgresql -I/usr/include/xmltok -pthread 
NOTEST_CPPFLAGS = 
EXTRA_CPPFLAGS = 
EXTRA_CFLAGS = 
