#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by /usr/src/linux-infrant-2.6/Kbuild
 *
 */

#define AOFF_task_thread 440 /* offsetof(struct task_struct, thread) */

#define AOFF_task_pid 180 /* offsetof(struct task_struct, pid) */
#define AOFF_task_uid 352 /* offsetof(struct task_struct, uid) */
#define AOFF_task_gid 368 /* offsetof(struct task_struct, gid) */
#define AOFF_task_euid 356 /* offsetof(struct task_struct, euid) */
#define AOFF_task_egid 372 /* offsetof(struct task_struct, egid) */
#define ASIZ_task_uid 4 /* sizeof(currentuid) */
#define ASIZ_task_gid 4 /* sizeof(currentgid) */
#define ASIZ_task_euid 4 /* sizeof(currenteuid) */
#define ASIZ_task_egid 4 /* sizeof(currentegid) */

#define AOFF_thread_fork_kpsr 8 /* offsetof(struct thread_struct, fork_kpsr) */

#define AOFF_mm_context 348 /* offsetof(struct mm_struct, context) */

#endif
