/* lineno 164 ctr 0 source ¡ uni ¡ ace xn--7a nv8 NV8 line B;	¡;	;	xn--7a;	NV8
 */
{ "¡", "xn--7a", -1 },
/* lineno 166 ctr 1 source  uni  ace  nv8  line B;	。;	[A4_2];	[A4_2]
 */
{ "", "", IDN2_OK },
/* lineno 269 ctr 2 source ☕ uni ☕ ace xn--53h nv8 NV8 line B;	☕;	;	xn--53h;	NV8
 */
{ "☕", "xn--53h", -1 },
/* lineno 272 ctr 3 source  uni  ace  nv8  line N;	1.aß\u200C\u200Db\u200C\u200Dcßßßßdςσßßßßßßßßeßßßßßßßßßßxßßßßßßßßßßyßßßßßßßß\u0302ßz;	[C1 C2];	[C1 C2 A4_2]	#	1.aß‌‍b‌‍cßßßßdςσßßßßßßßßeßßßßßßßßßßxßßßßßßßßßßyßßßßßßßß̂ßz
 */
{ "", "", IDN2_OK },
/* lineno 533 ctr 4 source xn--ss-1ju. uni ss" "\xe2\x83\x98" ". ace xn--ss-1ju. nv8 NV8 line B;	xn--ss-1ju.;	ss\u20D8.;	xn--ss-1ju.;	NV8	#	ss⃘.
 */
{ "ss" "\xe2\x83\x98" ".", "xn--ss-1ju.", -1 },
/* lineno 538 ctr 5 source  uni  ace  nv8  line N;	\uDB43\uDDD7\u200C⒈．\uDB40\uDF87;	[P1 V6 C1];	[P1 V6 C1]	#	󠷗‌⒈.󠎇
 */
{ "", "", IDN2_OK },
/* lineno 1024 ctr 6 source xn--56e26q0321avb7g.xn--h4h uni 🏨ᠣ" "\xe1\xaf\xb1" "" "\xed\xa0\x84" "" "\xed\xb7\x80" ".☠ ace xn--56e26q0321avb7g.xn--h4h nv8 NV8 line B;	xn--56e26q0321avb7g.xn--h4h;	🏨ᠣ\u1BF1\uD804\uDDC0.☠;	xn--56e26q0321avb7g.xn--h4h;	NV8	#	🏨ᠣᯱ𑇀.☠
 */
{ "🏨ᠣ" "\xe1\xaf\xb1" "" "\xed\xa0\x84" "" "\xed\xb7\x80" ".☠", "xn--56e26q0321avb7g.xn--h4h", -1 },
/* lineno 1027 ctr 7 source  uni  ace  nv8  line N;	\u0FAD\u200D\u08FB\u077A.\u0853\u200C\uDB40\uDF44;	[P1 V5 V6 B1 C2 B3 C1];	[P1 V5 V6 B1 C2 B3 C1]	#	ྭ‍ࣻݺ.ࡓ‌󠍄
 */
{ "", "", IDN2_OK },
/* lineno 2085 ctr 8 source xn--1-yn1bw30gq07b.6.xn--7xh uni ꡖ目姶1.6.╅ ace xn--1-yn1bw30gq07b.6.xn--7xh nv8 NV8 line B;	xn--1-yn1bw30gq07b.6.xn--7xh;	ꡖ目姶1.6.╅;	xn--1-yn1bw30gq07b.6.xn--7xh;	NV8
 */
{ "ꡖ目姶1.6.╅", "xn--1-yn1bw30gq07b.6.xn--7xh", -1 },
/* lineno 2087 ctr 9 source  uni  ace  nv8  line B;	\uD803\uDF7C.\uD803\uDE63≾\u0ACD;	[P1 V6 B1];	[P1 V6 B1]	#	𐽼.𐹣≾્
 */
{ "", "", IDN2_OK },
/* lineno 2916 ctr 10 source xn--16f130edj8dsszv.xn--e5h11w uni ⴜ𤮹" "\xe1\xb3\xa8" "舛.ⴏ♀ ace xn--16f130edj8dsszv.xn--e5h11w nv8 NV8 line B;	xn--16f130edj8dsszv.xn--e5h11w;	ⴜ𤮹\u1CE8舛.ⴏ♀;	xn--16f130edj8dsszv.xn--e5h11w;	NV8	#	ⴜ𤮹᳨舛.ⴏ♀
 */
{ "ⴜ𤮹" "\xe1\xb3\xa8" "舛.ⴏ♀", "xn--16f130edj8dsszv.xn--e5h11w", -1 },
/* lineno 2918 ctr 11 source  uni  ace  nv8  line B;	Ⴜ𤮹\u1CE8舛.Ⴏ♀;	[P1 V6];	[P1 V6]	#	Ⴜ𤮹᳨舛.Ⴏ♀
 */
{ "", "", IDN2_OK },
/* lineno 3486 ctr 12 source xn--88e.xn--pkj uni ᡬ.⳾ ace xn--88e.xn--pkj nv8 NV8 line B;	xn--88e.xn--pkj;	ᡬ.⳾;	xn--88e.xn--pkj;	NV8
 */
{ "ᡬ.⳾", "xn--88e.xn--pkj", -1 },
/* lineno 3489 ctr 13 source  uni  ace  nv8  line N;	쥥\uD95C\uDDABႮ．\u200C⒈⒈ᢝ;	[P1 V6 C1];	[P1 V6 C1]	#	쥥񧆫Ⴎ.‌⒈⒈ᢝ
 */
{ "", "", IDN2_OK },
/* lineno 3631 ctr 14 source 𝟱。🜎ᢧ uni 5.🜎ᢧ ace 5.xn--xbf5506v nv8 NV8 line B;	𝟱。🜎ᢧ;	5.🜎ᢧ;	5.xn--xbf5506v;	NV8
 */
{ "5.🜎ᢧ", "5.xn--xbf5506v", -1 },
/* lineno 3635 ctr 15 source  uni  ace  nv8  line B;	≮ꡌ。섖쮖ß;	[P1 V6];	[P1 V6]
 */
{ "", "", IDN2_OK },
/* lineno 4449 ctr 16 source 🁪.ⴂᠺ\u17143 uni 🁪.ⴂᠺ" "\xe1\x9c\x94" "3 ace xn--jw7h.xn--3-kpjx0e812d nv8 NV8 line B;	🁪.ⴂᠺ\u17143;	;	xn--jw7h.xn--3-kpjx0e812d;	NV8	#	🁪.ⴂᠺ᜔3
 */
{ "🁪.ⴂᠺ" "\xe1\x9c\x94" "3", "xn--jw7h.xn--3-kpjx0e812d", -1 },
/* lineno 4452 ctr 17 source  uni  ace  nv8  line B;	軥ᡋ.-\u031D;	[V3];	[V3]	#	軥ᡋ.-̝
 */
{ "", "", IDN2_OK },
/* lineno 4787 ctr 18 source xn--2gb0b.xn--zve uni " "\xd8\xb7" "" "\xd9\x89" ".᚜ ace xn--2gb0b.xn--zve nv8 NV8 line B;	xn--2gb0b.xn--zve;	\u0637\u0649.᚜;	xn--2gb0b.xn--zve;	NV8	#	طى.᚜
 */
{ "" "\xd8\xb7" "" "\xd9\x89" ".᚜", "xn--2gb0b.xn--zve", -1 },
/* lineno 4789 ctr 19 source  uni  ace  nv8  line B;	-\uD99D\uDF79.\u2DE5\u06A2-;	[P1 V3 V6 V5 B1];	[P1 V3 V6 V5 B1]	#	-񷝹.ⷥڢ-
 */
{ "", "", IDN2_OK },
