#! /bin/sh
# With multiple matches, grep -Fo could print a shorter one.
# This bug affected grep versions 2.26 through 2.27.
#
# Copyright (C) 2017 Free Software Foundation, Inc.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

. "${srcdir=.}/init.sh"; path_prepend_ ../src

fail=0

# The erroneous versions would print "c", rather than the longer match, "bce".
printf 'abce\n' > in || framework_failure_
printf 'abcd\nc\nbce\n' > pat || framework_failure_
printf 'bce\n' > exp || framework_failure_

LC_ALL=C grep -Fof pat in > out || fail=1
compare exp out || fail=1

Exit $fail
