#!/bin/sh
# Ensure that -m1 stops reading after the first match.
# In grep-2.19, yes x|grep -m1 x would infloop.

. "${srcdir=.}/init.sh"; path_prepend_ ../src
require_timeout_

fail=0

echo x > exp || framework_failure_

yes x | timeout 10 grep -m1 x > out || fail=1
compare exp out || fail=1

Exit $fail
