#!/bin/sh
# Trigger a bug in the DFA matcher.
# This would fail for grep-2.20.

# Copyright 2014-2017 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. "${srcdir=.}/init.sh"; path_prepend_ ../src

printf 'a\naa\n' > in || framework_failure_
printf 'aa\n' > exp || framework_failure_

fail=0

for LOC in en_US.UTF-8 en_US zh_CN $LOCALE_FR_UTF8 C; do
  out1=out1-$LOC
  LC_ALL=$LOC grep '..' in > out || fail=1
  compare exp out || fail=1
done

Exit $fail
