#!/bin/sh
# Test a pattern of multiple begin or end line constraints.
# This would mistakenly print a line when using grep-2.19.

# Copyright 2014-2017 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. "${srcdir=.}/init.sh"; path_prepend_ ../src

echo aa | grep 'a\(b$\|c$\)' >out && fail=1
compare /dev/null out || fail=1

echo aa | grep '\(^b\|^c\)a' >out && fail=1
compare /dev/null out || fail=1

Exit $fail
