#! /bin/sh
# Before grep-2.19, grep -P and -w/-x would not with a backreference.
#
# Copyright (C) 2014-2017 Free Software Foundation, Inc.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

. "${srcdir=.}/init.sh"; path_prepend_ ../src
require_pcre_

echo aa > in || framework_failure_
echo 'grep: reference to non-existent subpattern' > exp-err \
  || framework_failure_

fail=0

for xw in x w; do
  grep -P$xw '(.)\1' in > out 2>&1 || fail=1
  compare out in || fail=1

  grep -P$xw '(.)\2' in > out 2> err && fail=1
  compare /dev/null out || fail=1
  compare exp-err err || fail=1
done

Exit $fail
