#! /bin/sh
# grep -P / grep -Pc are inconsistent results
# This bug affected grep versions 2.21 through 2.22.
#
# Copyright (C) 2015-2017 Free Software Foundation, Inc.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

. "${srcdir=.}/init.sh"; path_prepend_ ../src
require_pcre_

fail=0

printf 'a\n%032768d\nb\0\n%032768d\na\n' 0 0 > in || framework_failure_

# grep will discover that the input is a binary file sooner if the
# page size is larger, so allow for either possible output.
printf 'a\nBinary file in matches\n' >exp1a || framework_failure_
printf 'Binary file in matches\n' >exp1b || framework_failure_
LC_ALL=C grep -P 'a' in >out || fail=1
compare exp1a out || compare exp1b out || fail=1

printf '2\n' >exp2 || framework_failure_
LC_ALL=C grep -Pc 'a' in >out || fail=1
compare exp2 out || fail=1

Exit $fail
