#! /bin/sh
# Ensure that grep -oaP doesn't infloop for invalid multi-byte input
#
# Copyright (C) 2015-2017 Free Software Foundation, Inc.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

. "${srcdir=.}/init.sh"; path_prepend_ ../src
require_timeout_
require_en_utf8_locale_
require_compiled_in_MB_support
LC_ALL=en_US.UTF-8 require_pcre_

fail=0

printf '\201_\0' > in || framework_failure_
printf '_\n' > exp || framework_failure_

LC_ALL=en_US.UTF-8 timeout 10 grep -aoP _ in > out 2> err || fail=1

compare exp out || fail=1
compare /dev/null err || fail=1

Exit $fail
