#!/bin/sh
# Check various bracket expressions in the POSIX locale.

# Copyright 2014-2017 Free Software Foundation, Inc.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. "${srcdir=.}/init.sh"; path_prepend_ ../src
LC_ALL=C
export LC_ALL

fail=0

echo a >in || framework_failure_
for bracketed in '[.a.]' '[.a.]-a' 'a-[.a.]' '[.a.]-[.a.]' \
    '[=a=]' '[:alpha:]' 'a-a[.-.]--'; do
  grep "[$bracketed]" in >out || fail=1
  compare in out || fail=1
  grep "[^$bracketed]" in >out
  test $? -eq 1 || fail=1
  compare /dev/null out || fail=1
done
Exit $fail
