#! /bin/sh
# Test for a bug in glibc's regex code as of September 7, 2014.
#
# Copyright (C) 2014-2017 Free Software Foundation, Inc.
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

. "${srcdir=.}/init.sh"; path_prepend_ ../src

echo a > in || framework_failure_

fail=0
grep -E '(.?)(.?)(.?)\3\2\1' in > out || fail=1
compare out in || fail=1

Exit $fail
