#!/bin/sh
# Use of any --include or --exclude* option would segfault in 2.6 and 2.6.1
. "${srcdir=.}/init.sh"; path_prepend_ ../src

echo f > x || framework_failure_
echo b >> x || framework_failure_
echo h >> x || framework_failure_
printf 'grep: character class syntax is [[:space:]], not [:space:]\n' \
  > exp-err || framework_failure_

# basic cases

returns_ 2 grep '[:space:]' x 2> err || fail=1
sed 's/^\([A-Za-z]:\)\{0,1\}[^: ]*: /grep: /' err > err1 && mv err1 err
compare exp-err err || fail=1

returns_ 1 grep '[[:space:]]' x 2> err || fail=1
test -s err && fail=1

# disabled by POSIXLY_CORRECT
returns_ 1 env POSIXLY_CORRECT=yes grep '[:space:]' x 2> err || fail=1
test -s err && fail=1

# patterns that are considered valid
returns_ 1 grep '[::]' x 2> err || fail=1
test -s err && fail=1

returns_ 1 grep '[:space]' x 2> err || fail=1
test -s err && fail=1

returns_ 1 grep '[:space:wxyz]' x 2> err || fail=1
test -s err && fail=1

returns_ 1 grep '[:space[:space:]:]' x 2> err || fail=1
test -s err && fail=1

returns_ 1 grep '[:spac-e:]' x 2> err || fail=1
test -s err && fail=1
Exit $fail
